# Generated by Django 3.1.4 on 2020-12-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20201217_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
    ]
