# Generated by Django 3.1.4 on 2020-12-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='projects'),
        ),
    ]
